name: .NET Framework Win Forms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Check GitHub Status
      uses: crazy-max/ghaction-github-status@v2
      with:
        overall_threshold: minor
        pages_threshold: partial_outage
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore Auto_Statistic.sln
     
    - name: Build
      run: msbuild Auto_Statistic.sln
